<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2016 Amasty (https://www.amasty.com)
 * @package Amasty_Label
 */
?>
<script type="text/javascript">
    var amlabel_selector = '<?php echo Mage::getStoreConfig('amlabel/options/selector')?>';
    <?php
        if (Mage::getStoreConfig('amlabel/options/use_js')) {
            echo Mage::registry('amlabel_scripts');
        }
    ?>
</script>