<?php if ($this->canShow()): ?>

<h2 class="table-caption front-rewardpoints-details-title"><?php echo $this->__('Reward Points Details') ?></h2>


<table cellspacing="0" width="100%" class="data-table front-rewardpoints-details">
    <colgroup>
        <col>
        <col width="1">
    </colgroup>
    
    <thead>
        <tr class="first last">
            <th><?php echo Mage::helper('rewardpoints')->__('Point Gathered') ?></th>
            <th class="a-right"><?php echo Mage::helper('rewardpoints')->__('Point Used') ?></th>
        </tr>
    </thead>
   
    <tbody>
        <tr>
            <td><?php echo $this->getPointsOnOrder(); ?></td>
            <td><?php echo $this->getPointsUsed();?></td>
        </tr>
    </tbody>
</table>

<?php endif;?>

