<div class="searchindex-result">
    <?php echo $this->getPager() ?>
    <ul>
        <?php foreach($this->getCollection() as $_content) : ?>
            <li>
                <div class="title">
                    <a href="<?php echo $_content->getUrl(); ?>"><?php echo $_content->getTitle() ?></a>
                </div>
            </li>
        <?php endforeach ?>
    </ul>
    <?php echo $this->getPager() ?>
</div>