<?php 
/**
* @author Amasty Team
* @copyright Copyright (c) 2013 Amasty (http://www.amasty.com)
* @package Amasty_Cart
*/

$_product = $this->getProduct(); 
$_helper = $this->helper('catalog/output');

//sitting Adding Configurable Products to Cart Settings
if(Mage::registry('simpleProduct'))
    $_simpleProduct = Mage::getModel('catalog/product')->load(Mage::registry('simpleProduct'));
    
if(Mage::getStoreConfig('amcart/configurable/name') && Mage::registry('simpleProduct') && $_simpleProduct->getName()){
    $_name = $_helper->productAttribute($_simpleProduct, $_simpleProduct->getName(), 'name');    
}else  
    $_name = $_helper->productAttribute($_product, $_product->getName(), 'name');
    
if(Mage::getStoreConfig('amcart/configurable/image') && Mage::registry('simpleProduct') && $_simpleProduct->getImage()){
    $_src = $this->helper('catalog/image')->init($_simpleProduct, 'image')->resize(135).'" alt="'.$this->htmlEscape($this->getImageLabel());
}else 
    $_src = $this->helper('catalog/image')->init($_product, 'image')->resize(135).'" alt="'.$this->htmlEscape($this->getImageLabel());
 

$_productNameStripped = $this->stripTags($_product->getName(), null, true); 

$_qty  = 1;
$product = (Mage::registry('simpleProduct'))? $_simpleProduct: $_product;
if($product->getTypeId() == 'simple'){
	$quote = Mage::helper('checkout/cart')->getCart()->getQuote();
	$collection = $quote->getItemsCollection()->addFieldToFilter('product_id', $product->getId())->load();
	$data = $collection->getData();
	if(array_key_exists(0, $data) && array_key_exists('qty', $data[0])) $_qty = (int)$data[0]['qty'];
}

?>
<p><?php echo $this->__('You have added ')?>
        <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $_productNameStripped; ?>">
            <?php echo $_name;?>
        </a>
   <?php echo $this->__(' to cart.')?>
</p>
<table style="width: 100%;">
    <tr>
        <td></td>
        
        <td style="height:135px; width:135px;">
                <?php
                    $_img = '<img src="'.$_src.'" title="'.$this->htmlEscape($this->getImageLabel()).'" />';
                    echo $_helper->productAttribute($_product, $_img, 'image');
                ?>
        </td>
        
        <td style="vertical-align: middle;">
            <?php if(Mage::getStoreConfig('amcart/general/display_qty') && !($this->getProduct()->getTypeId() == Mage_Catalog_Model_Product_Type::TYPE_BUNDLE || $this->getProduct()->isGrouped())):?>
            <script type="text/javascript">
                AmQtyObj = new AmQty(<?php echo $this->getProduct()->getStockItem()->getMinSaleQty();?>);
            </script>
                
             <div id="am-qty">
                <div style="width:60px; float:left;">
                    <div id="am-qty-button-up" class="am-qty" >
                        <img src="<?php echo $this->getSkinUrl('images/amasty/up.png')?>" onclick="AmQtyObj.increment()">
                    </div>
                    <div id="am-qty-input">
                        <input class="input-text qty" id="am-input" maxlength="12" title="Qty" size="7" onclick="AmQtyObj.paint()" onkeydown="if (event.keyCode == 13) AmQtyObj.update()" value="<?php echo $_qty;?>" name="cart[<?php echo Mage::helper('amcart')->getItemId($this->getProduct());?>][qty]">
			<input type="hidden" name="form_key" id="am-form-key" value="<?php echo Mage::getSingleton('core/session')->getFormKey(); ?>" />  
                    </div>
                     <div id="am-qty-button-down">
                        <img src="<?php echo $this->getSkinUrl('images/amasty/down.png')?>" onclick="AmQtyObj.decrement()" >
                    </div>
               </div> 
                 <div id="am-qty-button-update" style="display: none;">
                    <img src="<?php echo $this->getSkinUrl('images/amasty/refresh.png')?>" onclick="AmQtyObj.update()" >
                </div>
                <div style="clear: both;"></div>
            </div>    
            <?php endif;?>
    </td>
  </tr> 
</table>