<?php
	$theme = Mage::helper('ultimo');
?>
<meta http-equiv="Content-Type" content="<?php echo $this->getContentType() ?>" />
<title><?php echo $this->getTitle() ?></title>
<?php if ($theme->getCfgLayout('responsive/responsive')): ?>
	<meta name="viewport" content="width=device-width, initial-scale=1" />
	<?php //<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1" /> ?>
<?php endif; ?>
<meta name="description" content="<?php echo htmlspecialchars($this->getDescription()) ?>" />
<meta name="keywords" content="<?php echo htmlspecialchars($this->getKeywords()) ?>" />
<meta name="robots" content="<?php echo htmlspecialchars($this->getRobots()) ?>" />
<link rel="icon" href="<?php echo $this->getFaviconFile(); ?>" type="image/x-icon" />
<link rel="shortcut icon" href="<?php echo $this->getFaviconFile(); ?>" type="image/x-icon" />
<?php
	$skinUrl = $this->getSkinUrl('');
?>

<!--[if lt IE 7]>
<script type="text/javascript">
//<![CDATA[
    var BLANK_URL = '<?php echo $this->helper('core/js')->getJsUrl('blank.html') ?>';
    var BLANK_IMG = '<?php echo $this->helper('core/js')->getJsUrl('spacer.gif') ?>';
//]]>
</script>
<![endif]-->

<?php echo $this->getCssJsHtml() ?>
<?php echo $this->getChildHtml() ?>
<?php echo $this->helper('core/js')->getTranslatorScript() ?>
<?php echo $this->getIncludes() ?>

<?php //Include Google Fonts
	$amp = '&amp;';
	$charSubset = '';
	if ($subsets = $theme->getCfgDesign('font/primary_char_subset'))
	{
		$charSubset = "{$amp}subset={$subsets}";
	}

	$fontWeight = '';
	if ($weight = $theme->getCfgDesign('font/primary_font_weight'))
	{
		$fontWeight = ':' . $weight;
	}
?>
<?php if ($theme->getCfgDesign('font/primary_font_family_group') == 'google'): ?>
	<link href='//fonts.googleapis.com/css?family=<?php echo str_replace(' ', '+', $theme->getCfgDesign('font/primary_font_family')); 
		echo $fontWeight; echo $charSubset; ?>' rel='stylesheet' type='text/css' />
<?php endif;?>
