<?php 
/**
* @author Amasty Team
* @copyright Copyright (c) 2013 Amasty (http://www.amasty.com)
* @package Amasty_Cart
*/  
?>
<?php $items = $this->getItems();?>
<?php
if( $items->getSize() ):?>
<div class="block block-related" id="am-block-related">
    <p class="block-related-p"><?php echo $this->__('Related Products') ?></p>
    <div class="block-content">
        <table style="width: 100%;">
            <tr>
                <?php foreach( $items as $_item): ?>
                     <td>
                       <div class="product">
                            <a href="<?php echo $_item->getProductUrl() ?>" title="<?php echo $this->htmlEscape($_item->getName()) ?>" class="product-image">
                                <img src="<?php echo $this->helper('catalog/image')->init($_item, 'thumbnail')->resize(50) ?>" width="50" alt="<?php echo $this->htmlEscape($_item->getName()) ?>" />
                            </a>
                             <p class="product-name"><a href="<?php echo $_item->getProductUrl() ?>"><?php echo $this->htmlEscape($_item->getName()) ?></a></p>
                        </div>
                   </td>
                <?php endforeach ?>
           </tr>
           <tr>
             <?php foreach( $items as $_item): ?>
                <td style="vertical-align:bottom;">
                    <?php echo $this->getPriceHtml($_item, true, '-related') ?>
                    <br>
                    <div>
                     <button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart"><span><span><?php echo $this->__('Add to Cart') ?></span></span></button>
                    </div>
                </td>
             <?php endforeach ?>
          </tr>
      </table>
    </div>
    <script type="text/javascript">
        AmAjaxShoppCartLoad('#messageBox button.btn-cart');
    </script>
</div>
<?php endif ?>
