<?php
	$theme = Mage::helper('ultimo');
?>
<?php try{
	$geoIP = Mage::getSingleton('geoip/country');          
	$visitorCountry = $geoIP->getCountry();
} catch (Exception $e){ }?>
<?php if (isset($visitorCountry) && $visitorCountry!=="IL" && $visitorCountry!=="MX" ) :?>
    <script src="//cdn.optimizely.com/js/4314500412.js"></script>
<?php endif; ?>
<meta http-equiv="Content-Type" content="<?php echo $this->getContentType() ?>" />
<title><?php echo $this->getTitle() ?></title>
<?php if ($theme->getCfgLayout('responsive/responsive')): ?>
	<meta name="viewport" content="width=device-width, initial-scale=1" />
	<?php //<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1" /> ?>
<?php endif; ?>
<meta name="description" content="<?php echo htmlspecialchars($this->getDescription()) ?>" />
<meta name="keywords" content="<?php echo htmlspecialchars($this->getKeywords()) ?>" />
<meta name="robots" content="<?php echo htmlspecialchars($this->getRobots()) ?>" />
<link rel="icon" href="<?php echo $this->getFaviconFile(); ?>" type="image/x-icon" />
<link rel="shortcut icon" href="<?php echo $this->getFaviconFile(); ?>" type="image/x-icon" />

<?php /* Open Graph Protocol for Facebook and SEO START */ ?>
<?php if(Mage::registry('current_product')): ?>
 <?php $product = Mage::registry('current_product'); ?>
 <meta property="og:title" content="<?php echo ($product->getName()); ?>" />
 <meta property="og:type" content="product" />
 <meta property="og:image" content="<?php echo $this->helper('catalog/image')->init($product, 'small_image')->resize(200,200);?>" />
 <meta property="og:url" content="<?php echo Mage::registry('product')->getProductUrl(); ?>" />
 <meta property="og:description" content="<?php echo strip_tags(($product->getShortDescription())); ?>" />
<?php elseif(Mage::registry('current_category')): ?>
 <meta property="og:title" content="<?php echo $this->getTitle() ?>" />
 <meta property="og:type" content="product.group" />
 <meta property="og:image" content="http://www.housingcamera.com/media/wysiwyg/Og image.jpg" />
 <meta property="og:url" content="<?php echo $this->helper('core/url')->getCurrentUrl();?>" />
 <meta property="og:description" content="<?php echo strip_tags($this->getDescription()) ?>" />
<?php elseif((Mage::getSingleton('cms/page')->getIdentifier() == 'home' &&
 Mage::app()->getFrontController()->getRequest()->getRouteName() == 'cms')) : ?>
 <meta property="og:title" content="<?php echo $this->getTitle() ?>" />
 <meta property="og:type" content="website" />
  <meta property="og:image" content="http://www.housingcamera.com/media/wysiwyg/Og image.jpg" />
 <meta property="og:url" content="<?php echo $this->helper('core/url')->getCurrentUrl();?>" />
 <meta property="og:description" content="<?php echo strip_tags($this->getDescription()) ?>" />
<?php else: ?>
 <meta property="og:title" content="<?php echo $this->getTitle() ?>" />
 <meta property="og:type" content="article" />
  <meta property="og:image" content="http://www.housingcamera.com/media/wysiwyg/Og image.jpg" />
 <meta property="og:url" content="<?php echo $this->helper('core/url')->getCurrentUrl();?>" />
 <meta property="og:description" content="<?php echo strip_tags($this->getDescription()) ?>" />
<?php endif; ?>
<?php /* Open Graph Protocol for Facebook and SEO END */ ?>

<?php
	$skinUrl = $this->getSkinUrl('');
?>

<!--[if lt IE 7]>
<script type="text/javascript">
//<![CDATA[
    var BLANK_URL = '<?php echo $this->helper('core/js')->getJsUrl('blank.html') ?>';
    var BLANK_IMG = '<?php echo $this->helper('core/js')->getJsUrl('spacer.gif') ?>';
//]]>
</script>
<![endif]-->

<?php echo $this->getCssJsHtml() ?>
<?php echo $this->getChildHtml() ?>
<?php echo $this->helper('core/js')->getTranslatorScript() ?>
<?php echo $this->getIncludes() ?>

<?php //Include Google Fonts
	$amp = '&amp;';
	$charSubset = '';
	if ($subsets = $theme->getCfgDesign('font/primary_char_subset'))
	{
		$charSubset = "{$amp}subset={$subsets}";
	}

	$fontWeight = '';
	if ($weight = $theme->getCfgDesign('font/primary_font_weight'))
	{
		$fontWeight = ':' . $weight;
	}
?>
<?php if ($theme->getCfgDesign('font/primary_font_family_group') == 'google'): ?>
	<link href='//fonts.googleapis.com/css?family=<?php echo str_replace(' ', '+', $theme->getCfgDesign('font/primary_font_family')); 
		echo $fontWeight; echo $charSubset; ?>' rel='stylesheet' type='text/css' />
<?php endif;?>
