

<div class='entry-edit'>
    <div class="entry-edit-head"><h4 class="icon-head head-edit-form fieldset-legend"><?php echo $this->__('Category filter type'); ?></h4></div>
    <div class="fieldset" id='category-type'>

        <div class='main-box'>
            <script>
                document.observe('dom:loaded', function() {

                    if ($('simplegoogleshopping_category_filter').value == 1) {
                        $('category_filter_0').checked = false;
                        $('category_filter_1').checked = true;
                    }
                    else {
                        $('category_filter_0').checked = true;
                        $('category_filter_1').checked = false;
                    }
                    $$('.category_filter').each(function(r) {
                        r.observe('click', function() {

                            $('simplegoogleshopping_category_filter').value = r.value;
                        })
                    })

                    if ($('simplegoogleshopping_category_type').value == 1) {
                        $('category_type_0').checked = false;
                        $('category_type_1').checked = true;
                        $('category_type_2').checked = false;
                    }
                    else if ($('simplegoogleshopping_category_type').value == 2) {
                        $('category_type_0').checked = false;
                        $('category_type_1').checked = false;
                        $('category_type_2').checked = true;
                    }
                    else {
                        $('category_type_0').checked = true;
                        $('category_type_1').checked = false;
                        $('category_type_2').checked = false;
                    }
                    $$('.category_type').each(function(r) {
                        r.observe('click', function() {

                            $('simplegoogleshopping_category_type').value = r.value;

                        })
                    })
                })
            </script>
            <input type='radio' value='1' name='category_filter' class='category_filter' id="category_filter_1" /> <?php echo $this->__("<b>Include</b> all products from the selected categories."); ?><br/>
            <input type='radio' value='0' name='category_filter' class='category_filter' id="category_filter_0" /> <?php echo $this->__("<b>Exclude</b> all products from the selected categories."); ?><br/>
            <div style='padding:5px 0 0 0'>
                <b>Based on </b><br/>
                <input type="radio" value="0" name='category_type' class='category_type' id="category_type_0"/> <b>Product</b> categories only<br/>
                <input type="radio"  value="1" name='category_type' class='category_type' id="category_type_1"/> <b>Product and parent</b> categories<br/>
                <input type="radio"  value="2" name='category_type' class='category_type' id="category_type_2"/> <b>Parent</b> categories only<br/>                    

            </div>
        </div>
    </div>
    <div class="entry-edit-head"><h4 class="icon-head head-edit-form fieldset-legend"><?php echo $this->__('Category selection and mapping'); ?></h4></div>
    <div class="fieldset" id='category-selector'>
        <div id="taxonomy-box">

            <b><?php echo Mage::helper('simplegoogleshopping')->__("Google Taxonomy source : ") ?></b>  <select id="googleshopping_taxonomy" name='datafeed_taxonomy'>
                <?php

                function dirFiles($directory) {
                    $dir = dir($directory); //Open Directory
                    while (false !== ($file = $dir->read())) { //Reads Directory
                        $extension = substr($file, strrpos($file, '.')); // Gets the File Extension
                        if ($extension == ".txt") // Extensions Allowed
                            $filesall[$file] = $file; // Store in Array
                    }
                    $dir->close(); // Close Directory
                    asort($filesall); // Sorts the Array
                    return $filesall;
                }

                $io = new Varien_Io_File();
                $array = dirFiles($io->getCleanPath(Mage::getBaseDir() . "/lib/Wyomind/Google/Taxonomies/"));

                foreach ($array as $key => $file) {
                    if (Mage::registry('simplegoogleshopping_data')->getFeedTaxonomy() == "/lib/Wyomind/Google/Taxonomies/" . $file)
                        $selected = "selected";
                    else
                        $selected = "";
                    echo "<option value='" . "/lib/Wyomind/Google/Taxonomies/" . $file . "' $selected>" . basename(str_replace('.txt', null, $file)) . "</option>";
                }
                ?> 

            </select> 

        </div>
        <br>
        <div class='main-box'>
            <span id='note' style='margin-left:10px;'><?php echo $this->__("* If you do not select any category, all products will be exported") ?> </span>
            <?php
            $storeId = $this->getStoreId();
            $listOfCategories = Mage::getModel('catalog/category')->getCollection()
                    ->setStoreId($storeId)
                    ->addAttributeToSelect('name')

                    // ->addAttributeToSelect('is_active')
                    ->addAttributeToSort('path', 'ASC');

            $categories = array();
            foreach ($listOfCategories as $category) {
                if (substr($category->getPath(), 0, 2) == '1/' && $category->getLevel() > 0) {
                    $categories[$category->getId()]['name'] = $category->getName();
                    $categories[$category->getId()]['path'] = $category->getPath();
                    $categories[$category->getId()]['depth'] = count(explode('/', $category->getPath())) - 1;
                    $categories[$category->getId()]['id'] = $category->getId();
                }
            }

            //  array_shift($categories);


            $a = 0;
            $current_depth[$a] = 0;
            $a++;
            foreach ($categories as $category) {
                $current_depth[$a] = $category['depth'];
                if ($current_depth[$a] - $current_depth[$a - 1] > 1)
                    continue;
                //  print_r($category);
                //  echo "<br>";
                if ($current_depth[$a] > $current_depth[$a - 1])
                    echo "<ul class='categories-tree'>";
                elseif ($current_depth[$a] < $current_depth[$a - 1]) {
                    $ll = $current_depth[$a - 1] - $current_depth[$a];
                    for ($l = 0; $l < $ll; $l++) {
                        echo " </li></ul>";
                    }
                }
                echo "<li class='node'>
                                
				<div class='cat-box'>
                                        <div class='tree_view'></div>
                                        <input type='checkbox' id='category_" . $category['path'] . "' identifier='" . $category['path'] . "' class='category'/>" . strip_tags($category['name']) . " <span class='small'>[ID:" . $category['id'] . "]</span>
					
                                        <span class='mapped'><br><span>" . $this->__('mapped as') . " :</span></span> 
                                        <input title='Press `End.` on your keyboard in order to apply this value to all the sub-categories' type='text' class='mapping'  autocomplete='off' id='category_mapping" . $category['path'] . "' class='mapping' >
                                            <script type='text/javascript'> 
                                            new AutoComplete('category_mapping" . $category['path'] . "', '" . $this->getUrl('*/*/taxonomy') . "?s=', {cssClass:'autocomplete', delay: 0.25, resultFormat: AutoComplete.Options.RESULT_FORMAT_TEXT }); 
                                        </script>
				</div>";
                $a++;
            }
            echo "</li></ul>";
            ?>

        </div>
    </div>
</div>




