<?php
/**
 * Magento
 *
 * @category   design_default
 * @package    
 * @copyright  
 * @license    http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */
?>

<?php  if($this->getItemCount() > 0): ?>
<!-- Tal Added -->
<div class="block block-feed-reader feed-below-cat">
	<div class="block-content">
		<ul id="feed-items">
		<?php
                    $itemCount = 0;
                    foreach($this->getItems() as $item): ?>
			<li class="<?php echo (++$itemCount % 2 == 0 ? 'even' : 'odd'); ?><?php if($itemCount == 1): ?> first<?php endif;?><?php if($itemCount >= $this->getItemCount()): ?> last<?php endif; ?> grid12-6">                       
                            <div class="block-feed-item-txt grid12-12">
                                <h5>
                                    <a href="<?php echo $this->escapeHtml($item->link()); ?>">
                                            <?php echo $this->escapeHtml($item->title()); ?>
                                    </a>
                                </h5>
                                <p class="date">
                                    <?php //echo Mage::getModel('core/date')->date('F j, Y, g:i a', strtotime($item->pubDate())); ?>
                                </p>
                                <p class="summary">  
                                    <?php  $exerpt = strip_tags($item->description());
                                    echo substr($exerpt,0,150) . " ..."; ?>
                                    <a href="<?php echo $this->escapeHtml($item->link()); ?>" class="finder_contact" style="float:right;">Full Answer</a>
                                </p>
                            </div>
			</li>
		<?php if ($itemCount==4) break;
                      endforeach; ?>
		</ul>
	</div>
</div>
<?php endif;  ?>

